"""
Report generator: combines scored/summarized articles into Markdown, HTML, or JSON reports.

The executive summary and recommended actions are generated by Claude (cached system prompt).
"""

from __future__ import annotations

import json
import logging
import os
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

import anthropic
from jinja2 import Environment, FileSystemLoader

from src.models.article import SummarizedArticle
from src.summarizer.summarizer import group_summarized_by_impact

logger = logging.getLogger(__name__)

_REPORT_SYSTEM_PROMPT = (
    "You are a senior Amazon marketplace strategist who advises category leaders, CSMs, and account managers. "
    "You write sharp, data-informed intelligence that drives decisions — not filler. "
    "Every insight must pass the 'so what?' test: if a reader can't act on it differently than yesterday, cut it. "
    "Quantify where possible (%, $, timeframes, market share). Name specific brands, sellers, or regulations. "
    "Connect news events to second-order marketplace effects: ASP pressure, buy box shifts, search demand changes, "
    "seller churn risk, catalog gaps, or competitive repositioning opportunities. "
    "NEVER write generic advice like 'monitor the situation', 'consider restocking', or 'stay informed'. "
    "Write like a hedge fund analyst briefing a trader, not a corporate newsletter."
)

IMPACT_ORDER = ["Supply Chain", "Pricing", "Demand", "Regulatory", "Competitive", "Seasonal", "General"]


# ── LLM helpers ─────────────────────────────────────────────────────────────

def _call_llm(
    client: anthropic.Anthropic,
    model: str,
    max_tokens: int,
    prompt: str,
    max_retries: int = 3,
    base_delay: float = 1.0,
) -> str:
    for attempt in range(1, max_retries + 1):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=max_tokens,
                system=[
                    {
                        "type": "text",
                        "text": _REPORT_SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                messages=[{"role": "user", "content": prompt}],
            )
            usage = response.usage
            logger.debug(
                "LLM report call — input: %d, cache_create: %d, cache_read: %d, output: %d",
                usage.input_tokens,
                getattr(usage, "cache_creation_input_tokens", 0),
                getattr(usage, "cache_read_input_tokens", 0),
                usage.output_tokens,
            )
            return next(b.text for b in response.content if b.type == "text").strip()
        except anthropic.RateLimitError:
            wait = base_delay * (2 ** (attempt - 1))
            if attempt < max_retries:
                logger.warning("Rate limit on report LLM call — retrying in %.1fs", wait)
                time.sleep(wait)
            else:
                raise
        except anthropic.APIStatusError as exc:
            if exc.status_code >= 500 and attempt < max_retries:
                time.sleep(base_delay * (2 ** (attempt - 1)))
                continue
            raise
    raise RuntimeError("LLM retry exhausted")


def _generate_executive_summary(
    articles: list[SummarizedArticle],
    category: str,
    client: anthropic.Anthropic,
    model: str,
    max_retries: int,
    base_delay: float,
) -> list[str]:
    """Return 3-5 bullet point strings for the executive summary."""
    top = sorted(articles, key=lambda a: a.relevance_score, reverse=True)[:8]
    lines = "\n".join(
        f"- [{a.impact_type}/{a.impact_level}] {a.title}: {a.summary}"
        for a in top
    )
    prompt = (
        f"Category: {category}\n\n"
        f"Top articles this week:\n{lines}\n\n"
        "Write 3-5 executive summary bullet points. Each bullet must:\n"
        "- Lead with the strategic implication, not the headline\n"
        "- Quantify impact where data exists (%, $, timeframe, market share)\n"
        "- Name specific brands, companies, or regulations\n"
        "- Pass the 'so what?' test — a reader should understand why this matters to their P&L\n\n"
        "BAD: 'Supply chain disruptions may affect product availability'\n"
        "GOOD: 'Foxconn plant shutdown in Zhengzhou cuts iPhone assembly capacity ~30% through Q1, "
        "expect 2-3 week delay on accessory restocks as logistics bandwidth shifts to priority SKUs'\n\n"
        "Start each bullet with a dash (-). No headers, no numbered lists."
    )
    raw = _call_llm(client, model, 512, prompt, max_retries, base_delay)
    bullets = [
        line.lstrip("•-–— ").strip()
        for line in raw.splitlines()
        if line.strip().startswith(("-", "•", "–", "—"))
    ]
    return bullets[:5] if bullets else [raw[:300]]


def _generate_recommended_actions(
    articles: list[SummarizedArticle],
    category: str,
    client: anthropic.Anthropic,
    model: str,
    max_retries: int,
    base_delay: float,
) -> list[str]:
    """Return 3-5 recommended action strings for category managers."""
    high_med = [a for a in articles if a.impact_level in ("High", "Medium")]
    use = sorted(high_med, key=lambda a: a.relevance_score, reverse=True)[:6]
    lines = "\n".join(
        f"- [{a.impact_type}] {a.title}: {a.summary}"
        for a in use
    )
    prompt = (
        f"Category: {category}\n\n"
        f"Most impactful articles this week:\n{lines}\n\n"
        "Write 3-5 specific, actionable recommendations. Each must:\n"
        "- State a concrete action with a specific target (which ASINs, brands, or seller segments)\n"
        "- Include a timeframe or trigger ('by EOW', 'before tariff takes effect on July 1', 'if price drops below $X')\n"
        "- Explain the expected outcome or risk if not taken\n\n"
        "BAD: 'Monitor supply chain and consider restocking'\n"
        "GOOD: 'Pre-buy 4-6 weeks of [Brand] inventory before the 25% tariff hits Aug 1 — "
        "competitors who wait will face a $3-5 ASP increase and potential stockouts in weeks 3-4'\n\n"
        "NEVER use phrases like: 'monitor the situation', 'stay informed', 'consider adjusting', "
        "'keep an eye on'. Every recommendation must be a decision, not a suggestion to think about it.\n\n"
        "Start each recommendation with a dash (-). No headers."
    )
    raw = _call_llm(client, model, 512, prompt, max_retries, base_delay)
    actions = [
        line.lstrip("•-–— ").strip()
        for line in raw.splitlines()
        if line.strip().startswith(("-", "•", "–", "—"))
    ]
    return actions[:5] if actions else [raw[:300]]


# ── Template fallbacks (no LLM) ───────────────────────────────────────────────

# Generic playbook actions per impact type — used when no API key is available.
_TEMPLATE_ACTIONS_BY_TYPE: dict[str, list[str]] = {
    "Pricing": [
        "Review competitive pricing on affected SKUs and consider repricing rules.",
        "Flag affected ASINs for margin-impact review with finance.",
    ],
    "Supply Chain": [
        "Confirm inventory coverage for affected ASINs over the next 4-8 weeks.",
        "Engage backup suppliers and assess alternate-source readiness.",
    ],
    "Demand": [
        "Increase inventory positioning on trending SKUs and review forecast assumptions.",
        "Review search-term marketing spend on trending keywords.",
    ],
    "Regulatory": [
        "Audit affected listings for compliance with the new requirements.",
        "Coordinate with legal on potential recall or relisting actions.",
    ],
    "Competitive": [
        "Monitor competitor pricing and assortment changes weekly.",
        "Brief brand managers on the competitive event and its implications.",
    ],
    "Seasonal": [
        "Confirm seasonal inventory build matches the demand signal direction.",
        "Review promotion calendar alignment with the seasonal trigger.",
    ],
    "General": [
        "Review affected category for direct sales implications.",
    ],
}


def _template_executive_summary(articles: list[SummarizedArticle], category: str) -> list[str]:
    """Build an executive summary by surfacing the top headlines, no LLM needed."""
    if not articles:
        return ["No relevant articles found this week."]

    # Group highest-scoring article per impact type, up to 5 distinct types
    seen_types: set[str] = set()
    bullets: list[str] = []
    sorted_articles = sorted(articles, key=lambda a: a.relevance_score, reverse=True)
    for art in sorted_articles:
        if art.impact_type in seen_types:
            continue
        seen_types.add(art.impact_type)
        bullets.append(
            f"**{art.impact_type}** [{art.impact_level}]: {art.title} ({art.source})"
        )
        if len(bullets) >= 5:
            break

    # If fewer than 3 distinct types fired, top up with the next-highest-scoring articles
    if len(bullets) < 3:
        for art in sorted_articles:
            line = f"[{art.impact_level}] {art.title} ({art.source})"
            if not any(art.title in b for b in bullets):
                bullets.append(line)
            if len(bullets) >= 3:
                break

    return bullets[:5]


def _template_recommended_actions(articles: list[SummarizedArticle], category: str) -> list[str]:
    """Pick playbook actions for the impact types that fired this week."""
    if not articles:
        return ["No actionable items identified this week."]

    # Find the impact types with at least one High or Medium article, sorted by max score
    type_max_score: dict[str, int] = {}
    for a in articles:
        if a.impact_level in ("High", "Medium"):
            type_max_score[a.impact_type] = max(type_max_score.get(a.impact_type, 0), a.relevance_score)

    if not type_max_score:
        # Fall back to whatever we have
        for a in articles:
            type_max_score[a.impact_type] = max(type_max_score.get(a.impact_type, 0), a.relevance_score)

    sorted_types = sorted(type_max_score.items(), key=lambda kv: kv[1], reverse=True)

    actions: list[str] = []
    for impact_type, _ in sorted_types:
        for action in _TEMPLATE_ACTIONS_BY_TYPE.get(impact_type, []):
            if len(actions) >= 5:
                break
            actions.append(f"[{impact_type}] {action}")
        if len(actions) >= 5:
            break

    return actions[:5] if actions else ["Review high-impact articles and assess category-level implications."]


# ── Report data assembly ─────────────────────────────────────────────────────

def _date_range_str(days: int) -> tuple[str, str]:
    end = datetime.now(tz=timezone.utc)
    start = end - timedelta(days=days)
    fmt = "%b %-d, %Y"
    return start.strftime(fmt), end.strftime(fmt)


def build_report_data(
    category: str,
    articles_analyzed: int,
    summarized: list[SummarizedArticle],
    days: int,
    client: Optional[anthropic.Anthropic],
    model: str,
    max_retries: int,
    base_delay: float,
    sources_used: list[str],
) -> dict:
    """Assemble all report data into a serialisable dict."""
    date_start, date_end = _date_range_str(days)
    grouped = group_summarized_by_impact(summarized)

    exec_summary: list[str] = []
    actions: list[str] = []

    if not summarized:
        exec_summary = ["No relevant articles found this week."]
        actions = ["No actionable items identified this week."]
    elif client is None:
        # No API key — use template fallbacks
        logger.info("No Anthropic client — using template executive summary and actions.")
        exec_summary = _template_executive_summary(summarized, category)
        actions = _template_recommended_actions(summarized, category)
    else:
        try:
            exec_summary = _generate_executive_summary(summarized, category, client, model, max_retries, base_delay)
        except Exception as exc:
            logger.error("Executive summary generation failed: %s — using template fallback", exc)
            exec_summary = _template_executive_summary(summarized, category)
        try:
            actions = _generate_recommended_actions(summarized, category, client, model, max_retries, base_delay)
        except Exception as exc:
            logger.error("Recommended actions generation failed: %s — using template fallback", exc)
            actions = _template_recommended_actions(summarized, category)

    sections = []
    for impact_type in IMPACT_ORDER:
        group = grouped.get(impact_type, [])
        if not group:
            continue
        sections.append({
            "impact_type": impact_type,
            "articles": [a.to_dict() for a in group],
        })

    return {
        "category": category,
        "date_start": date_start,
        "date_end": date_end,
        "articles_analyzed": articles_analyzed,
        "relevant_articles": len(summarized),
        "executive_summary": exec_summary,
        "sections": sections,
        "recommended_actions": actions,
        "generated_at": datetime.now(tz=timezone.utc).isoformat(),
        "sources_used": sources_used,
        "disclaimer": (
            "This report is auto-generated from public news sources. "
            "Verify all claims before making business decisions."
        ),
    }


# ── Renderers ────────────────────────────────────────────────────────────────

def _render_markdown(data: dict) -> str:
    lines = []
    lines.append(f"# Category News Report: {data['category']}")
    lines.append(f"\n**Date Range:** {data['date_start']} – {data['date_end']}  ")
    lines.append(
        f"**Coverage:** {data['articles_analyzed']} articles scanned → "
        f"{data['relevant_articles']} relevant\n"
    )

    lines.append("---\n")
    lines.append("## Executive Summary\n")
    for bullet in data["executive_summary"]:
        lines.append(f"- {bullet}")

    lines.append("\n---\n")
    lines.append("## Detailed Findings\n")
    for section in data["sections"]:
        impact = section["impact_type"]
        lines.append(f"### {impact}\n")
        for art in section["articles"]:
            level_badge = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}.get(art["impact_level"], "⚪")
            lines.append(f"#### {level_badge} {art['title']}")
            pub = art.get("published_date") or "unknown"
            lines.append(f"**Source:** {art['source']} | **Date:** {pub} | **Score:** {art['relevance_score']}/100")
            lines.append(f"\n{art['summary']}\n")
            lines.append(f"> [Read more]({art['url']})\n")

    lines.append("---\n")
    lines.append("## Recommended Actions\n")
    for action in data["recommended_actions"]:
        lines.append(f"- {action}")

    lines.append("\n---\n")
    lines.append("## Report Details\n")
    lines.append(f"- **Generated:** {data['generated_at']}")
    lines.append(f"- **Sources:** {', '.join(data['sources_used'])}")
    lines.append(f"\n*{data['disclaimer']}*\n")

    return "\n".join(lines)


def _render_html(data: dict, template_dir: Optional[str] = None) -> str:
    if template_dir is None:
        template_dir = str(Path(__file__).parent / "templates")

    template_path = Path(template_dir) / "report.html.j2"
    if template_path.exists():
        env = Environment(
            loader=FileSystemLoader(template_dir),
            autoescape=True,
        )
        tmpl = env.get_template("report.html.j2")
        return tmpl.render(**data)

    # Inline fallback if template file is missing
    return _render_html_inline(data)


def _render_html_inline(data: dict) -> str:
    """Self-contained HTML with inline CSS — no external dependencies."""
    level_color = {"High": "#dc2626", "Medium": "#d97706", "Low": "#16a34a"}

    art_blocks = []
    for section in data["sections"]:
        articles_html = ""
        for art in section["articles"]:
            color = level_color.get(art["impact_level"], "#6b7280")
            pub = art.get("published_date") or "unknown"
            articles_html += f"""
            <div class="article">
              <h4><a href="{art['url']}">{art['title']}</a></h4>
              <div class="meta">
                <span style="color:{color};font-weight:bold;">{art['impact_level']}</span>
                &nbsp;·&nbsp;{art['source']}&nbsp;·&nbsp;{pub}
                &nbsp;·&nbsp;Score: {art['relevance_score']}/100
              </div>
              <p>{art['summary']}</p>
            </div>"""
        art_blocks.append(
            f'<section><h3>{section["impact_type"]}</h3>{articles_html}</section>'
        )

    exec_bullets = "".join(f"<li>{b}</li>" for b in data["executive_summary"])
    action_bullets = "".join(f"<li>{a}</li>" for a in data["recommended_actions"])
    source_list = ", ".join(data["sources_used"])
    sections_html = "\n".join(art_blocks)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Category Report: {data['category']}</title>
<style>
  body{{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1f2937;line-height:1.6}}
  h1{{font-size:1.8rem;border-bottom:3px solid #2563eb;padding-bottom:.5rem}}
  h2{{font-size:1.3rem;color:#1d4ed8;margin-top:2rem}}
  h3{{font-size:1.1rem;background:#f1f5f9;padding:.4rem .8rem;border-left:4px solid #2563eb;margin-top:1.5rem}}
  h4{{margin:.8rem 0 .2rem}}
  h4 a{{color:#1d4ed8;text-decoration:none}}
  h4 a:hover{{text-decoration:underline}}
  .meta{{font-size:.85rem;color:#6b7280;margin-bottom:.4rem}}
  .article{{border-bottom:1px solid #e5e7eb;padding-bottom:1rem;margin-bottom:1rem}}
  ul{{padding-left:1.5rem}}
  li{{margin:.3rem 0}}
  .header-box{{background:#eff6ff;border:1px solid #bfdbfe;border-radius:.5rem;padding:1rem 1.5rem;margin-bottom:1.5rem}}
  footer{{font-size:.8rem;color:#9ca3af;border-top:1px solid #e5e7eb;margin-top:2rem;padding-top:1rem}}
</style>
</head>
<body>
<div class="header-box">
  <h1>📰 Category News Report: {data['category']}</h1>
  <p>📅 {data['date_start']} – {data['date_end']}<br>
  📊 {data['articles_analyzed']} articles scanned → {data['relevant_articles']} relevant</p>
</div>

<h2>Executive Summary</h2>
<ul>{exec_bullets}</ul>

<h2>Detailed Findings</h2>
{sections_html}

<h2>Recommended Actions</h2>
<ul>{action_bullets}</ul>

<footer>
  <p>Generated: {data['generated_at']}<br>
  Sources: {source_list}<br>
  <em>{data['disclaimer']}</em></p>
</footer>
</body>
</html>"""


def _render_json(data: dict) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False)


# ── Save report ──────────────────────────────────────────────────────────────

def save_report(
    data: dict,
    fmt: str,
    output_dir: str = "reports",
    template_dir: Optional[str] = None,
) -> Path:
    """Render and save a report. Returns the saved file path."""
    slug = data["category"].lower().replace(" ", "_")
    date_slug = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    dir_ = Path(output_dir) / slug / date_slug
    dir_.mkdir(parents=True, exist_ok=True)

    ext = {"markdown": "md", "html": "html", "json": "json"}.get(fmt, "md")
    path = dir_ / f"report.{ext}"

    if fmt == "markdown":
        content = _render_markdown(data)
    elif fmt == "html":
        content = _render_html(data, template_dir)
    elif fmt == "json":
        content = _render_json(data)
    else:
        raise ValueError(f"Unknown format: {fmt!r}")

    path.write_text(content, encoding="utf-8")
    logger.info("Report saved to %s", path)
    return path
